### ISSUE TITLE
Transfer Shape Error

### ISSUE THREAD

**Issue by thecastlingking** [XuyangGuo/CtrlHair#10]
```
F:\Hair Filter\CtrlHair>python ui/frontend_demo.py
Network [SPADEGenerator] was created. Total number of parameters: 266.9 million. To see the architecture, do print(network).
 [*] Loading checkpoint succeeds! Copy variables from model_trained/color_texture/045__color_texture_final/checkpoints\0650000.ckpt!
 [*] Loading checkpoint succeeds! Copy variables from model_trained/color_encoder/p004___pca_std/checkpoints\0009295.ckpt!
 [*] Loading checkpoint succeeds! Copy variables from model_trained/shape/054__succeed__049__gan_fake_0.5_from_noise/checkpoints\0380000.ckpt!
'chmod' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
Traceback (most recent call last):
  File "ui/frontend_demo.py", line 179, in evt_trans_shape
    self.backend.transfer_latent_representation('shape', refresh=True)
  File ".\ui\backend.py", line 276, in transfer_latent_representation
    need_crop=False)
  File ".\wrap_codes\mask_adaptor.py", line 219, in wrap_by_imgs
    warp_temp_folder=wrap_temp_folder)
  File ".\wrap_codes\mask_adaptor.py", line 134, in hair_mask_transfer_wrap
    warp_temp_folder)
  File ".\wrap_codes\wrap_triangle\triangle_wrap_hair.py", line 53, in get_wrap_UV
    get_node(landmark_source, landmark_target, W, H, warp_temp_folder, numPoints=50)
  File ".\wrap_codes\wrap_triangle\step_3\generate_node.py", line 82, in get_node
    face_list = loadNode(os.path.join(saveFolder, 'albedo_landmarks.1.ele'))
  File ".\wrap_codes\wrap_triangle\step_3\generate_node.py", line 14, in loadNode
    with open(fileName) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_folder\\demo_output\\albedo_landmarks.1.ele'
```

Hey There, 

Hopefully you're be able to reply to this, I found an issue when I press the "Transfer Shape" button that I need solving. The 'albedo_landmarks.1.ele', file, I have no idea what this is and it seems that it needs to be in the temp_folder which is created during run time. Can you help me out?

(Also, just so you're aware, a number of the filenames in the code on the github do not match what is in the download folder filenames you provided. Not sure if you've changed the download folder files over time, but I had to change 3 or 4 file names.)

**Comment by kexul** [comment]
It seems to be a intermediate file, I'm not quite familiar with the code but I guess it could be raised when no facial landmarks are detected. 

PS: after modify some file path and numpy variable name, the code runs fine, at 2024/6/1.

**Comment by zxy0304** [comment]
> It seems to be a intermediate file, I'm not quite familiar with the code but I guess it could be raised when no facial landmarks are detected.
> 
> PS: after modify some file path and numpy variable name, the code runs fine, at 2024/6/1.

Would you mind give more detailed instruction about which path to modify? thx soooo much!

**Comment by kexul** [comment]
> > It seems to be a intermediate file, I'm not quite familiar with the code but I guess it could be raised when no facial landmarks are detected.
> > PS: after modify some file path and numpy variable name, the code runs fine, at 2024/6/1.
> 
> Would you mind give more detailed instruction about which path to modify? thx soooo much!

https://huggingface.co/kexul/ctrlhair check this, I've uploaded all the files.

**Comment by zxy0304** [comment]
> > > It seems to be a intermediate file, I'm not quite familiar with the code but I guess it could be raised when no facial landmarks are detected.
> > > PS: after modify some file path and numpy variable name, the code runs fine, at 2024/6/1.
> > 
> > 
> > Would you mind give more detailed instruction about which path to modify? thx soooo much!
> 
> https://huggingface.co/kexul/ctrlhair check this, I've uploaded all the files.

Thx for your response. Those modifications you upload help a lot! I've solved this issue now. Actually I try to run the code on windows platform, so I have to compile the triangle.c in berkeley_triangle folder and also my_arap.cpp to get the exe file for wins. And I have to rewrite several lines to let windows execute the original command to get_node and generate .ele files. If someone meet the same error, try this way.
