### ISSUE TITLE
ImportError: cannot import name 'mesh_core_cython'

### ISSUE THREAD

**Issue by RAOMMA** [XuyangGuo/CtrlHair#9]
Traceback (most recent call last):
  File "/content/CtrlHair/ui/frontend_demo.py", line 24, in <module>
    from ui.backend import Backend
  File "/content/CtrlHair/./ui/backend.py", line 25, in <module>
    from wrap_codes.mask_adaptor import wrap_by_imgs
  File "/content/CtrlHair/./wrap_codes/mask_adaptor.py", line 6, in <module>
    from wrap_codes.wrap_triangle import triangle_wrap_hair
  File "/content/CtrlHair/./wrap_codes/wrap_triangle/triangle_wrap_hair.py", line 12, in <module>
    from wrap_codes.wrap_triangle.step_4.help_warp import get_warpedUV
  File "/content/CtrlHair/./wrap_codes/wrap_triangle/step_4/help_warp.py", line 9, in <module>
    from external_code.my_cython import mesh_core_cython
  File "/content/CtrlHair/./external_code/my_cython/__init__.py", line 3, in <module>
    from . import mesh_core_cython
ImportError: cannot import name 'mesh_core_cython' from partially initialized module 'external_code.my_cython' (most likely due to a circular import) (/content/CtrlHair/./external_code/my_cython/__init__.py)

**Comment by NicolaGugole** [comment]
+1 with the above.

**Comment by RAOMMA** [comment]
@NicolaGugole I solved this using the following command
cd CtrlHair/external_code/my_cython
python setup.py build_ext --inplace
